### Create a new report
# POST http://localhost:3000/reports
POST https://calm-sea-34981.herokuapp.com/reports
Content-Type: application/json

{
    "make": "Honda",
    "model": "City",
    "year": 1982,
    "mileage": 50000,
    "lng": 45,
    "lat": 45,
    "price": 10000
}

### Approve a report with its given id
# PATCH  http://localhost:3000/reports/1
PATCH https://calm-sea-34981.herokuapp.com/reports/3
Content-Type: application/json

{
    "approved": true
}

### Get an estimate
# GET http://localhost:3000/reports?make=Honda&model=City&year=1980&mileage=50000&lng=45&lat=45
GET https://calm-sea-34981.herokuapp.com/reports?make=Honda&model=City&year=1980&mileage=50000&lng=45&lat=45