### Create a new report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "TOYOTA",
    "model": "Fortuner",
    "year": 2015,
    "mileage": 500320,
    "lng": 0,
    "lat": 0,
    "price": 500000
}