### Create a new report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "TATA",
    "model": "Indica",
    "year": 2014,
    "mileage": 37272,
    "lng": 0,
    "lat": 0,
    "price": 255265
}

### Approve a report with its given id
PATCH  http://localhost:3000/reports/5
Content-Type: application/json

{
    "approved": true
}